# Generated by Django 4.0.4 on 2022-04-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor1', 'Indoor'), ('Outdoor1', 'Outdoor')], max_length=200, null=True),
        ),
    ]
